name = "cryptic-key-system"
main = "src/index.js"
compatibility_date = "2026-09-18"

# Nach dem Erstellen der KV-Namespaces (siehe README) hier die IDs eintragen:
kv_namespaces = [
  { binding = "KV", id = "15532578ec2e44b7baa5b20d6294e33d" }
]

# Diese Werte werden NICHT hier eingetragen, sondern als Secrets gesetzt
# (siehe README): ADMIN_PASS, TURNSTILE_SECRET
#
# Diesen Wert kannst du normal als Variable setzen (ist öffentlich, kein Geheimnis):
[vars]
TURNSTILE_SITEKEY = "0x4AAAAAAE7iqGCztCrwijja"
